version: '3.8'

services:
  geminicli2api:
    build: .
    # 'ports' section is removed to allow Coolify's reverse proxy to manage traffic.
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    environment:
      - GEMINI_AUTH_PASSWORD=${GEMINI_AUTH_PASSWORD}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8888}
    volumes:
      # Mount the credentials folder
      - ./credentials:/app/credentials:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-8888}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
